repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/prettier/prettier
    sha: 1.10.2
    hooks:
      - id: prettier
        name: prettier
        # Prettier runs on JavaScript as part of eslint
        exclude_types: [ javascript ]
        exclude: ^package\.json
  - repo: https://github.com/standard/standard
    rev: master
    hooks:
      - id: standard
  - repo: local
    hooks:
      - id: husky-run-pre-commit
        name: husky
        language: system
        entry: node_modules/.bin/husky-run pre-commit
        pass_filenames: false
        always_run: true
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: 0.9.1
#    hooks:
#      - id: detect-secrets
#        args: [ '--baseline', '.secrets.baseline' ]
#        exclude: tests/.*
